# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from __future__ import annotations

from typing import Union, Optional
from typing_extensions import Literal, Required, Annotated, TypeAlias, TypedDict

from ..._types import SequenceNotStr
from ..._utils import PropertyInfo

__all__ = [
    "InferencePipelineCreateParams",
    "DataBackend",
    "DataBackendBigQueryDataBackend",
    "DataBackendBigQueryDataBackendConfig",
    "DataBackendDefaultDataBackend",
    "DataBackendSnowflakeDataBackend",
    "DataBackendSnowflakeDataBackendConfig",
    "DataBackendDatabricksDtlDataBackend",
    "DataBackendDatabricksDtlDataBackendConfig",
    "DataBackendRedshiftDataBackend",
    "DataBackendRedshiftDataBackendConfig",
    "DataBackendPostgresDataBackend",
    "DataBackendPostgresDataBackendConfig",
    "Project",
    "Workspace",
]


class InferencePipelineCreateParams(TypedDict, total=False):
    description: Required[Optional[str]]
    """The inference pipeline description."""

    name: Required[str]
    """The inference pipeline name."""

    data_backend: Annotated[Optional[DataBackend], PropertyInfo(alias="dataBackend")]

    project: Optional[Project]

    workspace: Optional[Workspace]


class DataBackendBigQueryDataBackendConfig(TypedDict, total=False):
    ground_truth_column_name: Annotated[Optional[str], PropertyInfo(alias="groundTruthColumnName")]
    """Name of the column with the ground truths."""

    human_feedback_column_name: Annotated[Optional[str], PropertyInfo(alias="humanFeedbackColumnName")]
    """Name of the column with human feedback."""

    inference_id_column_name: Annotated[Optional[str], PropertyInfo(alias="inferenceIdColumnName")]
    """Name of the column with the inference ids.

    This is useful if you want to update rows at a later point in time. If not
    provided, a unique id is generated by Openlayer.
    """

    latency_column_name: Annotated[Optional[str], PropertyInfo(alias="latencyColumnName")]
    """Name of the column with the latencies."""

    timestamp_column_name: Annotated[Optional[str], PropertyInfo(alias="timestampColumnName")]
    """Name of the column with the timestamps.

    Timestamps must be in UNIX sec format. If not provided, the upload timestamp is
    used.
    """


class DataBackendBigQueryDataBackend(TypedDict, total=False):
    backend_type: Required[Annotated[Literal["bigquery"], PropertyInfo(alias="backendType")]]

    bigquery_connection_id: Required[Annotated[Optional[str], PropertyInfo(alias="bigqueryConnectionId")]]

    config: Required[DataBackendBigQueryDataBackendConfig]

    dataset_id: Required[Annotated[str, PropertyInfo(alias="datasetId")]]

    project_id: Required[Annotated[str, PropertyInfo(alias="projectId")]]

    table_id: Required[Annotated[Optional[str], PropertyInfo(alias="tableId")]]

    partition_type: Annotated[Optional[Literal["DAY", "MONTH", "YEAR"]], PropertyInfo(alias="partitionType")]


class DataBackendDefaultDataBackend(TypedDict, total=False):
    backend_type: Required[Annotated[Literal["default"], PropertyInfo(alias="backendType")]]


class DataBackendSnowflakeDataBackendConfig(TypedDict, total=False):
    ground_truth_column_name: Annotated[Optional[str], PropertyInfo(alias="groundTruthColumnName")]
    """Name of the column with the ground truths."""

    human_feedback_column_name: Annotated[Optional[str], PropertyInfo(alias="humanFeedbackColumnName")]
    """Name of the column with human feedback."""

    inference_id_column_name: Annotated[Optional[str], PropertyInfo(alias="inferenceIdColumnName")]
    """Name of the column with the inference ids.

    This is useful if you want to update rows at a later point in time. If not
    provided, a unique id is generated by Openlayer.
    """

    latency_column_name: Annotated[Optional[str], PropertyInfo(alias="latencyColumnName")]
    """Name of the column with the latencies."""

    timestamp_column_name: Annotated[Optional[str], PropertyInfo(alias="timestampColumnName")]
    """Name of the column with the timestamps.

    Timestamps must be in UNIX sec format. If not provided, the upload timestamp is
    used.
    """


class DataBackendSnowflakeDataBackend(TypedDict, total=False):
    backend_type: Required[Annotated[Literal["snowflake"], PropertyInfo(alias="backendType")]]

    config: Required[DataBackendSnowflakeDataBackendConfig]

    database: Required[str]

    schema: Required[str]

    snowflake_connection_id: Required[Annotated[Optional[str], PropertyInfo(alias="snowflakeConnectionId")]]

    table: Required[Optional[str]]


class DataBackendDatabricksDtlDataBackendConfig(TypedDict, total=False):
    ground_truth_column_name: Annotated[Optional[str], PropertyInfo(alias="groundTruthColumnName")]
    """Name of the column with the ground truths."""

    human_feedback_column_name: Annotated[Optional[str], PropertyInfo(alias="humanFeedbackColumnName")]
    """Name of the column with human feedback."""

    inference_id_column_name: Annotated[Optional[str], PropertyInfo(alias="inferenceIdColumnName")]
    """Name of the column with the inference ids.

    This is useful if you want to update rows at a later point in time. If not
    provided, a unique id is generated by Openlayer.
    """

    latency_column_name: Annotated[Optional[str], PropertyInfo(alias="latencyColumnName")]
    """Name of the column with the latencies."""

    timestamp_column_name: Annotated[Optional[str], PropertyInfo(alias="timestampColumnName")]
    """Name of the column with the timestamps.

    Timestamps must be in UNIX sec format. If not provided, the upload timestamp is
    used.
    """


class DataBackendDatabricksDtlDataBackend(TypedDict, total=False):
    backend_type: Required[Annotated[Literal["databricks_dtl"], PropertyInfo(alias="backendType")]]

    config: Required[DataBackendDatabricksDtlDataBackendConfig]

    databricks_dtl_connection_id: Required[Annotated[Optional[str], PropertyInfo(alias="databricksDtlConnectionId")]]

    table_id: Required[Annotated[Optional[str], PropertyInfo(alias="tableId")]]


class DataBackendRedshiftDataBackendConfig(TypedDict, total=False):
    ground_truth_column_name: Annotated[Optional[str], PropertyInfo(alias="groundTruthColumnName")]
    """Name of the column with the ground truths."""

    human_feedback_column_name: Annotated[Optional[str], PropertyInfo(alias="humanFeedbackColumnName")]
    """Name of the column with human feedback."""

    inference_id_column_name: Annotated[Optional[str], PropertyInfo(alias="inferenceIdColumnName")]
    """Name of the column with the inference ids.

    This is useful if you want to update rows at a later point in time. If not
    provided, a unique id is generated by Openlayer.
    """

    latency_column_name: Annotated[Optional[str], PropertyInfo(alias="latencyColumnName")]
    """Name of the column with the latencies."""

    timestamp_column_name: Annotated[Optional[str], PropertyInfo(alias="timestampColumnName")]
    """Name of the column with the timestamps.

    Timestamps must be in UNIX sec format. If not provided, the upload timestamp is
    used.
    """


class DataBackendRedshiftDataBackend(TypedDict, total=False):
    backend_type: Required[Annotated[Literal["redshift"], PropertyInfo(alias="backendType")]]

    config: Required[DataBackendRedshiftDataBackendConfig]

    redshift_connection_id: Required[Annotated[Optional[str], PropertyInfo(alias="redshiftConnectionId")]]

    schema_name: Required[Annotated[str, PropertyInfo(alias="schemaName")]]

    table_name: Required[Annotated[str, PropertyInfo(alias="tableName")]]


class DataBackendPostgresDataBackendConfig(TypedDict, total=False):
    ground_truth_column_name: Annotated[Optional[str], PropertyInfo(alias="groundTruthColumnName")]
    """Name of the column with the ground truths."""

    human_feedback_column_name: Annotated[Optional[str], PropertyInfo(alias="humanFeedbackColumnName")]
    """Name of the column with human feedback."""

    inference_id_column_name: Annotated[Optional[str], PropertyInfo(alias="inferenceIdColumnName")]
    """Name of the column with the inference ids.

    This is useful if you want to update rows at a later point in time. If not
    provided, a unique id is generated by Openlayer.
    """

    latency_column_name: Annotated[Optional[str], PropertyInfo(alias="latencyColumnName")]
    """Name of the column with the latencies."""

    timestamp_column_name: Annotated[Optional[str], PropertyInfo(alias="timestampColumnName")]
    """Name of the column with the timestamps.

    Timestamps must be in UNIX sec format. If not provided, the upload timestamp is
    used.
    """


class DataBackendPostgresDataBackend(TypedDict, total=False):
    backend_type: Required[Annotated[Literal["postgres"], PropertyInfo(alias="backendType")]]

    config: Required[DataBackendPostgresDataBackendConfig]

    database: Required[str]

    postgres_connection_id: Required[Annotated[Optional[str], PropertyInfo(alias="postgresConnectionId")]]

    schema: Required[str]

    table: Required[Optional[str]]


DataBackend: TypeAlias = Union[
    DataBackendBigQueryDataBackend,
    DataBackendDefaultDataBackend,
    DataBackendSnowflakeDataBackend,
    DataBackendDatabricksDtlDataBackend,
    DataBackendRedshiftDataBackend,
    DataBackendPostgresDataBackend,
]


class Project(TypedDict, total=False):
    name: Required[str]
    """The project name."""

    task_type: Required[
        Annotated[
            Literal["llm-base", "tabular-classification", "tabular-regression", "text-classification"],
            PropertyInfo(alias="taskType"),
        ]
    ]
    """The task type of the project."""

    description: Optional[str]
    """The project description."""


class Workspace(TypedDict, total=False):
    name: Required[str]
    """The workspace name."""

    slug: Required[str]
    """The workspace slug."""

    invite_code: Annotated[str, PropertyInfo(alias="inviteCode")]
    """The workspace invite code."""

    saml_only_access: Annotated[bool, PropertyInfo(alias="samlOnlyAccess")]
    """Whether the workspace only allows SAML authentication."""

    wildcard_domains: Annotated[SequenceNotStr[str], PropertyInfo(alias="wildcardDomains")]
